/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.PaginaPadre;
import Utils.Utils;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author desarrollo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        PromptSupport.setPrompt("Nombre archivo", this.jTextFieldNombreArchivo);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, this.jTextFieldNombreArchivo);
        PromptSupport.setPrompt("Nombre red", this.jTextFieldNombreRed);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, this.jTextFieldNombreRed);
        PromptSupport.setPrompt("Equipo red", this.jTextFieldNombreEquipoRed);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, this.jTextFieldNombreEquipoRed);
        PromptSupport.setPrompt("Mensaje archivo", this.jTextAreaMensaje);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, this.jTextAreaMensaje);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIniciarAplicacion = new javax.swing.JButton();
        jButtonDetenerAplicacion = new javax.swing.JButton();
        jButtonEnviarMensaje = new javax.swing.JButton();
        jTextFieldNombreArchivo = new javax.swing.JTextField();
        jTextFieldNombreRed = new javax.swing.JTextField();
        jTextFieldNombreEquipoRed = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensaje = new javax.swing.JTextArea();
        jComboBoxAccion = new javax.swing.JComboBox();
        jMenuInicio = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jItemConfiguracion = new javax.swing.JMenuItem();
        jItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setResizable(false);

        jButtonIniciarAplicacion.setText("Iniciar Aplicación");
        jButtonIniciarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarAplicacionActionPerformed(evt);
            }
        });

        jButtonDetenerAplicacion.setText("Detener Aplicación");

        jButtonEnviarMensaje.setText("Enviar mensaje");
        jButtonEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarMensajeActionPerformed(evt);
            }
        });

        jTextFieldNombreArchivo.setToolTipText("Nombre del archivo");
        jTextFieldNombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreArchivoActionPerformed(evt);
            }
        });

        jTextFieldNombreRed.setToolTipText("Nombre del archivo");
        jTextFieldNombreRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreRedActionPerformed(evt);
            }
        });

        jTextFieldNombreEquipoRed.setToolTipText("Nombre del archivo");
        jTextFieldNombreEquipoRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreEquipoRedActionPerformed(evt);
            }
        });

        jTextAreaMensaje.setColumns(20);
        jTextAreaMensaje.setLineWrap(true);
        jTextAreaMensaje.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMensaje);

        jComboBoxAccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Crear", "Consultar", "Modificar", "Eliminar" }));

        jMenuPrincipal.setText("Archivo");
        jMenuPrincipal.setToolTipText("");

        jItemConfiguracion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ALT, 0));
        jItemConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/configure_shortcuts.png"))); // NOI18N
        jItemConfiguracion.setText("Configuracion");
        jItemConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemConfiguracionActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jItemConfiguracion);

        jItemSalir.setText("Salir");
        jItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemSalirActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jItemSalir);

        jMenuInicio.add(jMenuPrincipal);

        setJMenuBar(jMenuInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonIniciarAplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDetenerAplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jButtonEnviarMensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNombreEquipoRed, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreRed, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreEquipoRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEnviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIniciarAplicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDetenerAplicacion)
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jItemConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemConfiguracionActionPerformed
        Configuracion configuracion = new Configuracion(this);
    }//GEN-LAST:event_jItemConfiguracionActionPerformed

    private void jItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jItemSalirActionPerformed

    private void jButtonIniciarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarAplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIniciarAplicacionActionPerformed

    private void jButtonEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarMensajeActionPerformed
        if (!Utils.AplicacionIniciada)
            JOptionPane.showMessageDialog(this, "Debe iniciar la aplicación.");
    }//GEN-LAST:event_jButtonEnviarMensajeActionPerformed

    private void jTextFieldNombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreArchivoActionPerformed

    private void jTextFieldNombreRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreRedActionPerformed

    private void jTextFieldNombreEquipoRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreEquipoRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreEquipoRedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetenerAplicacion;
    private javax.swing.JButton jButtonEnviarMensaje;
    private javax.swing.JButton jButtonIniciarAplicacion;
    private javax.swing.JComboBox jComboBoxAccion;
    private javax.swing.JMenuItem jItemConfiguracion;
    private javax.swing.JMenuItem jItemSalir;
    private javax.swing.JMenuBar jMenuInicio;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMensaje;
    private javax.swing.JTextField jTextFieldNombreArchivo;
    private javax.swing.JTextField jTextFieldNombreEquipoRed;
    private javax.swing.JTextField jTextFieldNombreRed;
    // End of variables declaration//GEN-END:variables
}
